# Generated by Django 2.2 on 2020-02-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_author_app', '0002_auto_20200214_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
