# Generated by Django 2.2 on 2020-02-25 00:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('token', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teachers', models.ManyToManyField(related_name='students', to='school_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.TextField()),
                ('grades', models.IntegerField()),
                ('notes', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('graded', models.BooleanField()),
                ('submitted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(related_name='assignments', to='school_app.Student')),
                ('teachers', models.ManyToManyField(related_name='assignments', to='school_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('number', models.IntegerField()),
                ('subject', models.TextField()),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school_app.Teacher')),
                ('students', models.ManyToManyField(related_name='courses', to='school_app.Student')),
            ],
        ),
    ]
