# Generated by Django 2.2 on 2020-02-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
