# Generated by Django 2.2 on 2020-02-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='marcelo'),
            preserve_default=False,
        ),
    ]
